### ISSUE TITLE
Incorrect video title for "cache management extra 2"

### ISSUE THREAD

**Issue by ValentinH** [kentcdodds/bookshelf#156]
In [this lesson](https://epicreact.dev/modules/build-an-epic-react-app/cache-management-extra-credit-solution-02), the title is incorrect both in the webapp and in the video:
![image](https://user-images.githubusercontent.com/2678610/103881812-3c05b900-50db-11eb-962e-20e7e7fdf0a1.png)

![image](https://user-images.githubusercontent.com/2678610/103881838-4758e480-50db-11eb-993a-2a5fee18f7e2.png)

I think it should be "Wrap the `<App />` in a `<ReactQueryConfigProvider />`".

I can make a PR for the webapp list text, but I don't know for the video title.

**Comment by kentcdodds** [comment]
Thanks Valentin! @dealingwith will get this resolved :)

**Comment by kentcdodds** [comment]
This has been fixed. Thanks again!

**Comment by ValentinH** [comment]
I don't know it's related to this change but I now see a weird layout on the right menu:
![image](https://user-images.githubusercontent.com/2678610/104131140-dd5b6c00-5374-11eb-9669-411582687019.png)

**Comment by kentcdodds** [comment]
Thanks! I'll let the team know.

**Comment by dealingwith** [comment]
> I don't know it's related to this change but I now see a weird layout on the right menu:

I can't seem to reproduce. I'm in Chrome.

![Screenshot from 2021-01-10 23-19-15](https://user-images.githubusercontent.com/124208/104149028-5ae5a300-539a-11eb-9f0e-83a366971371.png)

More narrow viewport:

![Screenshot from 2021-01-10 23-19-22](https://user-images.githubusercontent.com/124208/104149033-5de09380-539a-11eb-8aed-8aed18f88080.png)

**Comment by ValentinH** [comment]
I'm using Brave on MacOS:
![image](https://user-images.githubusercontent.com/2678610/104201996-a5aefb80-542a-11eb-8d22-619654615891.png)

This only happen when I refresh the page when a specific lesson like https://epicreact.dev/modules/build-an-epic-react-app/make-http-requests-intro

I tried clearing the cache, the local storage and even in private mode without any extension and I still get the issue.
If I click on another video, then it works fine.

After inspecting the DOM, I could noticed that different classes were applied when the bug was happening and when it was not.

With the bug:
![image](https://user-images.githubusercontent.com/2678610/104202547-59b08680-542b-11eb-9f6e-6b1ea8a4c4a1.png)

Without the bug:
![image](https://user-images.githubusercontent.com/2678610/104202600-67fea280-542b-11eb-988d-a62d597a925e.png)

**Comment by dealingwith** [comment]
I just tested again in Brave Version 1.18.78 Chromium: 87.0.4280.141 -- although this is on Ubuntu -- and still can't reproduce the bug. Are there any assets not loading in the dev tools Network tab?

**Comment by ValentinH** [comment]
No issues with assets loading.

**Comment by kentcdodds** [comment]
@dealingwith figured out how to reproduce the bug and we're tracking progress on it. Thanks!
